spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xunban
    username: root
    password: ybwell
logging:
  level:
    com.xunban.mapper: debug

#????????
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
